### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by hvdklauw** [cfpb/drama-free-django#11]
https://github.com/cfpb/drama-free-django/blob/master/no_drama/__main__.py#L27

**Comment by chosak** [comment]
@hvdklauw thanks for reporting this issue. Unfortunately, drama-free-django is not yet compatible with Python 3, when this syntax becomes invalid. When this repository is updated to fully support Python 3, we'll fix this and all similarly invalid syntax.
