### ISSUE TITLE
Bug: String formatting in sitecustomize.py causes errors with passwords that include unmatched { or }

### ISSUE THREAD

**Issue by willbarton** [cfpb/drama-free-django#13]
The string formatting in [sitecustomize.py](https://github.com/cfpb/drama-free-django/blob/master/no_drama/build_skel/lib/sitecustomize.py#L20-L21) can have issues if values contain unmatched `{` or `}` characters. This is a distinctly possible scenario when we're dealing with values that are passwords. 

The problematic code is here:

```python
interpolated = {key: value.format(**resolved_paths)
                for key, value in new_env_vars.items()}
```

For every value in the environment.json file, `.format()` gets called.

It's possible to escape `{` but if a password is `my{S3cure{P4ssw0rd` then it would have to be written as `my{{S3cure{{P4ssw0rd` in the Ansible vault from which the the environment.json file is populated, which means anyone looking up the password will have to remember this or else be extremely frustrated when the password doesn't work.

**Comment by rosskarchner** [comment]
I wonder if the interpolation feature is even used?
